
export const SeedStyles = [
    {name: "Streetwear", scenario: "Everyday city look for hangouts or campus.", vibe_tags: ['urban', 'relaxed', 'youthful']},
    {name: "Casual Everyday", scenario: "Default outfit for errands, coffee, or casual hangouts.", vibe_tags: ['simple', 'classic', 'low-effort']},
    {name: "Smart Casual", scenario: "Casual Friday at the office or dinner after work.", vibe_tags: ['office', 'date', 'smart']},
    {name: "Rugged Workwear", scenario: "Chilly weekend in the countryside or at a cabin.", vibe_tags: ['outdoor', 'warm', 'classic']},
    {name: "Techwear", scenario: "Night city walk or creative event.", vibe_tags: ['dark', 'futuristic', 'urban']},
    {name: "Old Money", scenario: "Lunch or early dinner at a private club or nice restaurant.", vibe_tags: ['preppy', 'elegant', 'daytime']},
    {name: "Minimalist Modern", scenario: "Any casual day where you want a sharp, easy outfit.", vibe_tags: ['monochrome', 'clean', 'modern']},
    {name: "Athleisure", scenario: "Light workout followed by coffee or errands.", vibe_tags: ['sporty', 'functional', 'casual']},
    {name: "Business Casual", scenario: "Everyday office outfit in a casual corporate environment.", vibe_tags: ['office', 'classic', 'neat']},
    {name: "E-Boy", scenario: "Classic E-boy everyday outfit.", vibe_tags: ['layered', 'alt', 'youthful']},
    {name: "Hyperclean Techwear", scenario: "Cool, windy day commuting through the city or going to a tech meetup.", vibe_tags: ['monochrome', 'technical', 'urban']},
    {name: "Creative Corporate", scenario: "Standard day at a modern tech or creative office.", vibe_tags: ['smart_casual', 'modern', 'approachable']},
    {name: "Urban Safari", scenario: "City exploring or museum day.", vibe_tags: ['utility', 'smart_casual', 'neutral']},
    {name: "Quiet Luxury Sport", scenario: "Casual office day or lunch meeting.", vibe_tags: ['smart_casual', 'neutral', 'polished']},
    {name: "Neo-Y2K Minimal", scenario: "Casual day out or meeting friends.", vibe_tags: ['baggy', 'minimal', 'retro']},
    {name: "Studio Uniform", scenario: "Everyday studio work or casual office.", vibe_tags: ['uniform', 'minimal', 'easy']},
    {name: "Cyber-Linen", scenario: "Warm city day, brunch, or seaside walk.", vibe_tags: ['light', 'breathable', 'minimal']},
    {name: "Soft Metal", scenario: "Dinner date or evening drinks.", vibe_tags: ['elevated', 'soft_sheen', 'evening']},
    {name: "Symmetry Streetwear", scenario: "Casual hangout or street walk.", vibe_tags: ['balanced', 'graphic', 'casual']},
    {name: "Monochrome Geometry", scenario: "Cooler days, gallery visits, or creative office.", vibe_tags: ['geometric', 'minimal', 'smart_casual']},
    {name: "Business Formal", scenario: "Important client presentation or board meeting.", vibe_tags: ['authoritative', 'polished', 'classic']},
    {name: "Bohemian", scenario: "Daytime music festival in warm weather.", vibe_tags: ['festival', 'free_spirited', 'breezy']},
    {name: "Gothic", scenario: "Night out at a goth/industrial club.", vibe_tags: ['dark', 'dramatic', 'edgy']},
    {name: "Romantic Aesthetic", scenario: "Casual dinner date or evening coffee.", vibe_tags: ['soft', 'approachable', 'evening']},
    {name: "Scandinavian Style", scenario: "Daily commute or casual office.", vibe_tags: ['minimal', 'clean', 'urban']},
];