export const StyleImages: Record<string, any> = {
    "Streetwear": require('../assets/styles/Streetwear.jpg'),
    "Casual Everyday": require('../assets/styles/Casual_Everyday.jpg'),
    "Smart Casual": require('../assets/styles/Smart_Casual.jpg'),
    "Rugged Workwear": require('../assets/styles/Rugged_Workwear.jpg'),
    "Techwear": require('../assets/styles/Techwear.jpg'),
    "Old Money": require('../assets/styles/Old_Money.jpg'),
    "Minimalist Modern": require('../assets/styles/Minimalist_Modern.jpg'),
    "Athleisure": require('../assets/styles/Athleisure.jpg'),
    "Business Casual": require('../assets/styles/Business_Casual.jpg'),
    "E-Boy": require('../assets/styles/E-Boy.jpg'),
    "Hyperclean Techwear": require('../assets/styles/Hyperclean_Techwear.jpg'),
    "Creative Corporate": require('../assets/styles/Creative_Corporate.jpg'),
    "Urban Safari": require('../assets/styles/Urban_Safari.jpg'),
    "Quiet Luxury Sport": require('../assets/styles/Quiet_Luxury_Sport.jpg'),
    "Neo-Y2K Minimal": require('../assets/styles/Neo-Y2K_Minimal.jpg'),
    "Studio Uniform": require('../assets/styles/Studio_Uniform.jpg'),
    "Cyber-Linen": require('../assets/styles/Cyber-Linen.jpg'),
    "Soft Metal": require('../assets/styles/Soft_Metal.jpg'),
    "Symmetry Streetwear": require('../assets/styles/Symmetry_Streetwear.jpg'),
    "Monochrome Geometry": require('../assets/styles/Monochrome_Geometry.jpg'),
    "Business Formal": require('../assets/styles/Business_Formal.jpg'),
    "Bohemian": require('../assets/styles/Bohemian.jpg'),
    "Gothic": require('../assets/styles/Gothic.jpg'),
    "Romantic Aesthetic": require('../assets/styles/Romantic_Aesthetic.jpg'),
    "Scandinavian Style": require('../assets/styles/Scandinavian_Style.jpg'),
};
